DROP DATABASE IF EXISTS EJEMPLO;

CREATE DATABASE EJEMPLO;

USE EJEMPLO;

CREATE TABLE Personas(
	PersonaID 		INT NOT NULL AUTO_INCREMENT,
	Nombre 			VARCHAR(20) NOT NULL,
	Pais 			VARCHAR(20) NOT NULL,
	Telefono		VARCHAR(10) NOT NULL,
	Direccion 		VARCHAR(20) NOT NULL,
	Correo			VARCHAR(50) NOT NULL,
	PRIMARY KEY (PersonaID)
);

select * from Personas;